### ISSUE TITLE
user input not working for some users

### ISSUE THREAD

**Issue by ghost** [darkwarrior3/termuxstyling#1]
read -p "Type your username: " *uname* </dev/tty
echo "This is your username: *$uname*"
echo "*$uname*" > DW.config
# the var is not set by user input

**Comment by ghost** [comment]
Bug solved

**Comment by e6ing** [comment]
How can i manually change the font color?

**Comment by darkwarrior3** [comment]
> How can i manually change the font color?

green="\e[1;92m"
red="\e[1;91m"
blue="\e[1;94m"
purple="\e[35m"
yellow="\e[1;93m"
pink="\e[1;95m"
skyblue="\e[1;96m"
white="\e[1;97m"
